version: "3.7"

services:
  impactodo_database:
    image: postgres
    container_name: impactodo_database
    stdin_open: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=impactodo_database
    volumes:
      - pgdata:/data/postgres
  impactodo_test_database:
    image: postgres
    container_name: impactodo_test_database
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=impactodo_test_database
    volumes:
      - pgdata:/data/postgres
  impactodo_api:
    build: ./server
    container_name: impactodo_api
    ports:
      - 3333:3333
    volumes:
      - ./server:/usr/app
    links:
      - impactodo_database
    depends_on:
      - impactodo_database
  impactodo_web:
    build: ./web
    container_name: impactodo_web
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/app

volumes:
  pgdata:
    driver: local
